version: 0.2

env:
  variables:
    AWS_REGION: "us-east-1"  # Change this if needed
    ECR_REPOSITORY: "awsdevops"  # Your ECR repository name
    IMAGE_URI: "381492039554.dkr.ecr.us-east-1.amazonaws.com/awsdevops"

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $IMAGE_URI

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t $IMAGE_URI .

  post_build:
    commands:
      - echo "Pushing Docker image to Amazon ECR..."
      - docker push $IMAGE_URI
      - echo "Build completed successfully!"

artifacts:
  files:
    - "**/*"
  name: build-output